services:
  - type: web
    name: bigjpg-upscaler
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BIGJPG_API_KEY
        sync: false
